DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS city;

CREATE TABLE City (
  id INT generated BY DEFAULT AS identity,
  city_name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Ticket (
  id INT generated BY DEFAULT AS identity,
    ticket_cost DECIMAL NOT NULL,
    ticket_date DATE,
    from_city INT,
    to_city INT,
  PRIMARY KEY (id),
  CONSTRAINT FK_Direction_from FOREIGN KEY (from_city) REFERENCES City (id),
  CONSTRAINT FK_Direction_to FOREIGN KEY (to_city) REFERENCES City (id)
);

CREATE TABLE Payment (
  id INT generated BY DEFAULT AS identity,
  payment_date  DATE,
  ticket_id INT NOT NULL,
  email VARCHAR(255),
  PRIMARY KEY (id),
  FOREIGN KEY (ticket_id) REFERENCES Ticket (id)
);
