//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.26 at 06:29:37 PM MSK 
//


package com.epam.brest2019.courses.soap.model.payment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.brest2019.courses.soap.model.payment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.brest2019.courses.soap.model.payment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllPaymentResponse }
     * 
     */
    public GetAllPaymentResponse createGetAllPaymentResponse() {
        return new GetAllPaymentResponse();
    }

    /**
     * Create an instance of {@link PaymentSoap }
     * 
     */
    public PaymentSoap createPaymentSoap() {
        return new PaymentSoap();
    }

    /**
     * Create an instance of {@link GetPaymentByIdResponse }
     * 
     */
    public GetPaymentByIdResponse createGetPaymentByIdResponse() {
        return new GetPaymentByIdResponse();
    }

    /**
     * Create an instance of {@link GetUpdatePaymentRequest }
     * 
     */
    public GetUpdatePaymentRequest createGetUpdatePaymentRequest() {
        return new GetUpdatePaymentRequest();
    }

    /**
     * Create an instance of {@link GetDeletePaymentRequest }
     * 
     */
    public GetDeletePaymentRequest createGetDeletePaymentRequest() {
        return new GetDeletePaymentRequest();
    }

    /**
     * Create an instance of {@link GetPaymentByIdRequest }
     * 
     */
    public GetPaymentByIdRequest createGetPaymentByIdRequest() {
        return new GetPaymentByIdRequest();
    }

    /**
     * Create an instance of {@link GetAddPaymentRequest }
     * 
     */
    public GetAddPaymentRequest createGetAddPaymentRequest() {
        return new GetAddPaymentRequest();
    }

    /**
     * Create an instance of {@link GetAllPaymentRequest }
     * 
     */
    public GetAllPaymentRequest createGetAllPaymentRequest() {
        return new GetAllPaymentRequest();
    }

}
