//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.30 at 12:53:39 PM MSK 
//


package com.epam.brest2019.courses.model.soap.model.ticket;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.brest2019.courses.model.soap.model.ticket package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.brest2019.courses.model.soap.model.ticket
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSearchTicketByDateAndDirectionRequest }
     * 
     */
    public GetSearchTicketByDateAndDirectionRequest createGetSearchTicketByDateAndDirectionRequest() {
        return new GetSearchTicketByDateAndDirectionRequest();
    }

    /**
     * Create an instance of {@link GetAllTicketWithDirectionRequest }
     * 
     */
    public GetAllTicketWithDirectionRequest createGetAllTicketWithDirectionRequest() {
        return new GetAllTicketWithDirectionRequest();
    }

    /**
     * Create an instance of {@link GetAllTicketRequest }
     * 
     */
    public GetAllTicketRequest createGetAllTicketRequest() {
        return new GetAllTicketRequest();
    }

    /**
     * Create an instance of {@link GetTicketByIdResponse }
     * 
     */
    public GetTicketByIdResponse createGetTicketByIdResponse() {
        return new GetTicketByIdResponse();
    }

    /**
     * Create an instance of {@link TicketSoap }
     * 
     */
    public TicketSoap createTicketSoap() {
        return new TicketSoap();
    }

    /**
     * Create an instance of {@link GetTicketByIdRequest }
     * 
     */
    public GetTicketByIdRequest createGetTicketByIdRequest() {
        return new GetTicketByIdRequest();
    }

    /**
     * Create an instance of {@link GetSearchTicketByDateAndDirectionResponse }
     * 
     */
    public GetSearchTicketByDateAndDirectionResponse createGetSearchTicketByDateAndDirectionResponse() {
        return new GetSearchTicketByDateAndDirectionResponse();
    }

    /**
     * Create an instance of {@link GetAddTicketRequest }
     * 
     */
    public GetAddTicketRequest createGetAddTicketRequest() {
        return new GetAddTicketRequest();
    }

    /**
     * Create an instance of {@link GetAllTicketResponse }
     * 
     */
    public GetAllTicketResponse createGetAllTicketResponse() {
        return new GetAllTicketResponse();
    }

    /**
     * Create an instance of {@link GetAllTicketWithDirectionResponse }
     * 
     */
    public GetAllTicketWithDirectionResponse createGetAllTicketWithDirectionResponse() {
        return new GetAllTicketWithDirectionResponse();
    }

    /**
     * Create an instance of {@link GetUpdateTicketRequest }
     * 
     */
    public GetUpdateTicketRequest createGetUpdateTicketRequest() {
        return new GetUpdateTicketRequest();
    }

    /**
     * Create an instance of {@link GetDeleteTicketRequest }
     * 
     */
    public GetDeleteTicketRequest createGetDeleteTicketRequest() {
        return new GetDeleteTicketRequest();
    }

}
