//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.30 at 12:53:39 PM MSK 
//


package com.epam.brest2019.courses.model.soap.model.payment;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.epam.brest2019.courses.model.soap.model.ticket.TicketSoap;


/**
 * <p>Java class for paymentSoap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paymentSoap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paymentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="paymentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ticketId" type="{http://epam.com/brest2019/courses/soap/model/ticket}ticketSoap"/>
 *         &lt;element name="ticketCost" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ticketCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paymentSoap", propOrder = {
    "paymentId",
    "paymentDate",
    "email",
    "ticketId",
    "ticketCost",
    "ticketCount"
})
public class PaymentSoap {

    protected int paymentId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paymentDate;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected TicketSoap ticketId;
    @XmlElement(required = true)
    protected BigDecimal ticketCost;
    protected long ticketCount;

    /**
     * Gets the value of the paymentId property.
     * 
     */
    public int getPaymentId() {
        return paymentId;
    }

    /**
     * Sets the value of the paymentId property.
     * 
     */
    public void setPaymentId(int value) {
        this.paymentId = value;
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentDate(XMLGregorianCalendar value) {
        this.paymentDate = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the ticketId property.
     * 
     * @return
     *     possible object is
     *     {@link TicketSoap }
     *     
     */
    public TicketSoap getTicketId() {
        return ticketId;
    }

    /**
     * Sets the value of the ticketId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketSoap }
     *     
     */
    public void setTicketId(TicketSoap value) {
        this.ticketId = value;
    }

    /**
     * Gets the value of the ticketCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTicketCost() {
        return ticketCost;
    }

    /**
     * Sets the value of the ticketCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTicketCost(BigDecimal value) {
        this.ticketCost = value;
    }

    /**
     * Gets the value of the ticketCount property.
     * 
     */
    public long getTicketCount() {
        return ticketCount;
    }

    /**
     * Sets the value of the ticketCount property.
     * 
     */
    public void setTicketCount(long value) {
        this.ticketCount = value;
    }

}
