//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.30 at 12:53:39 PM MSK 
//


package com.epam.brest2019.courses.model.soap.model.city;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.brest2019.courses.model.soap.model.city package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.brest2019.courses.model.soap.model.city
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllCityRequest }
     * 
     */
    public GetAllCityRequest createGetAllCityRequest() {
        return new GetAllCityRequest();
    }

    /**
     * Create an instance of {@link GetCityByIdResponse }
     * 
     */
    public GetCityByIdResponse createGetCityByIdResponse() {
        return new GetCityByIdResponse();
    }

    /**
     * Create an instance of {@link CitySoap }
     * 
     */
    public CitySoap createCitySoap() {
        return new CitySoap();
    }

    /**
     * Create an instance of {@link GetDeleteCityRequest }
     * 
     */
    public GetDeleteCityRequest createGetDeleteCityRequest() {
        return new GetDeleteCityRequest();
    }

    /**
     * Create an instance of {@link GetCityByIdRequest }
     * 
     */
    public GetCityByIdRequest createGetCityByIdRequest() {
        return new GetCityByIdRequest();
    }

    /**
     * Create an instance of {@link GetUpdateCityRequest }
     * 
     */
    public GetUpdateCityRequest createGetUpdateCityRequest() {
        return new GetUpdateCityRequest();
    }

    /**
     * Create an instance of {@link GetAllCityResponse }
     * 
     */
    public GetAllCityResponse createGetAllCityResponse() {
        return new GetAllCityResponse();
    }

    /**
     * Create an instance of {@link GetAddCityRequest }
     * 
     */
    public GetAddCityRequest createGetAddCityRequest() {
        return new GetAddCityRequest();
    }

}
